import java.util.HashMap;
import java.util.Map;

public class Bank {
    private Map<String, Account> accountsByMobile = new HashMap<>();
        private int accountCounter = 1000; // Simple counter to generate unique account numbers

            public void createAccount(String mobileNumber, String name, int age) {
                    if (accountsByMobile.containsKey(mobileNumber)) {
                                System.out.println("Account already exists for mobile number: " + mobileNumber);
                                            return;
                                                    }

                                                            String accountNumber = "AC" + (accountCounter++);
                                                                    Account newAccount;
                                                                            if (age < 18) {
                                                                                        newAccount = new StudentAccount(accountNumber, name, 0.0, true);
                                                                                                } else {
                                                                                                            newAccount = new WorkingAccount(accountNumber, name, 0.0, true);
                                                                                                                    }
                                                                                                                            accountsByMobile.put(mobileNumber, newAccount);
                                                                                                                                    System.out.println("Account created successfully for mobile number: " + mobileNumber);
                                                                                                                                        }

                                                                                                                                            public void handleMonthlyUpdates() {
                                                                                                                                                    for (Account account : accountsByMobile.values()) {
                                                                                                                                                                account.handleMonthlyCharges();
                                                                                                                                                                        }
                                                                                                                                                                            }

                                                                                                                                                                                public void printAccountDetails(String mobileNumber) {
                                                                                                                                                                                        Account account = accountsByMobile.get(mobileNumber);
                                                                                                                                                                                                if (account != null) {
                                                                                                                                                                                                            account.printAccountDetails();
                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                System.out.println("No account found for mobile number: " + mobileNumber);
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    public static void main(String[] args) {
                                                                                                                                                                                                                                                            Bank bank = new Bank();
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            // Create accounts
                                                                                                                                                                                                                                                                                    bank.createAccount("1234567890", "Alice Smith", 17);
                                                                                                                                                                                                                                                                                            bank.createAccount("0987654321", "Bob Johnson", 25);
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                            // Print account details
                                                                                                                                                                                                                                                                                                                    bank.printAccountDetails("1234567890");
                                                                                                                                                                                                                                                                                                                            bank.printAccountDetails("0987654321");
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            // Simulate monthly updates
                                                                                                                                                                                                                                                                                                                                                    bank.handleMonthlyUpdates();
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                    // Print account details again to see the updates
                                                                                                                                                                                                                                                                                                                                                                            bank.printAccountDetails("1234567890");
                                                                                                                                                                                                                                                                                                                                                                                    bank.printAccountDetails("0987654321");
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        